myproduct/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include('products.urls')),
]

products/urls.py
from django.conf.urls import url
from . import views
app_name = "products_app"
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name="index"),
	url(r'^lists', views.home, name='home'),
	url(r'^create/$', views.template_to_create, name='create'),
	url(r'^(?P<product_id>[0-9]+)specific/$', views.specifics, name='specific'),
	url(r'^detail/$', views.create, name='detail'),
	url(r'^register/$', views.Register.as_view(), name="register"),
	url(r'^register_user/$', views.register_user, name='register_user'),
	url(r'^login/$', views.login_user, name='login'),
	url(r'^logout/$', views.logout_user, name="logout"),
]

products/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Product(models.Model):
  created = models.DateTimeField(auto_now_add= True)
  name = models.CharField(max_length=100, blank=True, default="")
  price = models.DecimalField(max_digits=20, decimal_places=2)
  description = models.TextField(max_length=300, default='')
  quantity = models.IntegerField()
  user = models.ForeignKey(User, on_delete=models.CASCADE, default="")


  class Meta:
    ordering =('name',)

products/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Product
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate

# Create your views here.

def home(request):
    product_list = Product.objects.order_by('created')[:20]
    context = {
        "product_list": product_list,
    }
    
    return render(request, "products/home.html", context)
# class Create_p(TemplateView):
#     template_name = 'myproduct_app/detail.html'

def create(request):
    data= request.POST
    Product.objects.create(
        name = data['name'],
        price = data['price'],
        description = data['description'],
        quantity = data['quantity'],
        user=request.user
        )
    return HttpResponseRedirect(redirect_to="/products/lists")

def template_to_create(request):
    return render(request, "products/detail.html")


def specifics(request):
    product_item = Product.objects.get(pk=product_id)
    context = {
    "product_item": product_item
    }
    return render(request, "products/specific.html", context )

class IndexView(TemplateView):
    template_name = "products/login.html"


class Register(TemplateView):
    template_name = 'products/register.html'

def register_user(request):
    data = request.POST
    User.objects.create(
        username=data['username'],
        email=data['email'],
        password=data['password'],
        first_name=data['first_name'],
        last_name=data['last_name'],
        )
    return login_user(request)

def login_user(request):
    data=request.POST
    username=data['username']
    password=data['password']
    user=authenticate(
        username=username,
        password=password)
    if user is not None:
        login(request=request, user=user)
    else:
        return HttpResponseRedirect(redirect_to='/')
    return HttpResponseRedirect(redirect_to='/products/lists')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(redirect_to='/')

products/templates/products/detail.html
{%extends 'products/index.html'%}
{% block content %}
<form class="" action="{% url 'products_app:detail' %}" method="post">
		{% csrf_token %}
		<input type="text" name="name" value="" placeholder="name">
		<input type="text" name="price" value="" placeholder="price">
		<input type="text" name="description" value="" placeholder="description">
		<input type="text" name="quantity" value="" placeholder="quantity">
		<button type="submit">Submit</button>
</form>

{%endblock%}

products/templates/products/home.html
{% extends 'products/index.html'%}
{%block content%}

{%if product_list %}
	<ul>
	{% for product in product_list %}
		<li><a href="/products/{{product_id}}/">Product:{{product.name}}
		</a></li>
		<li>Price:{{product.price}}</li>
		<li>Description:{{product.description}}</li>
		<li>Quantity:{{product.quantity}}</li>
		<li>User:{{product.user}}</li>

	{% endfor %}

	</ul>
{% else %}
	<p> No products are avaiable.</p>

{%endif%}
{%endblock%}

products/templates/products/index.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django My Products</title>
    <link rel="stylesheet" hre="{%static 'main.css'%}">
  </head>
  <body>
    {% block content %}{% endblock %}
    <script type="text/javascript" src="{%static 'main.js'%}"></script>
  </body>
</html>

products/templates/products/login.html
{%extends 'products/index.html'%}
{%block content%}
<form class = "" action="{url products_app:list}" method="post">
	{%csrf_token%}
	<input type="text" name='username' value="" placeholder="Enter username">
	<input type="text" name='password' value="" placeholder="Enter password">
	<button type="submit">Submit</button>
</form>
<p>Not a user register<a href="{%url 'products_app:register'%}">HERE </a></p>

{%endblock%}

products/templates/products/register.html
{% extends 'products/index.html'%}

{% block content %}
<form class="" action="{% url 'products_app:register_user' %}" method="post">
		{% csrf_token %}
		<input type="text" name="username" value="" placeholder="username">
		<input type="text" name="email" value="" placeholder="email">
		<input type="text" name="password" value="" placeholder="password">
		<input type="text" name="first_name" value="" placeholder="first_name">
		<input type="text" name="last_name" value="" placeholder="last_name">
		<button type="submit">Submit</button>
</form>

{%endblock%}
	

products/templates/products/specific.html
{% extends 'products/index.html'%}
{%block content%}

{%if product_list %}
	<ul>
	{% for product in product_list %}
		<li><a href="/products/{{product_id}}/">Product:{{product.name}}
		</a></li>
		<li>Price:{{product.price}}</li>
		<li>Description:{{product.description}}</li>
		<li>Quantity:{{product.quantity}}</li>

	{% endfor %}

	</ul>
{% else %}
	<p> No products are avaiable.</p>

{%endif%}
{%endblock%}